/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_BDWGC_BOX__
#define __RUST_BDWGC_BOX__
#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

/** <No documentation available> */
int32_t
consume_box (
    int32_t * gc);

/** <No documentation available> */
int32_t
consume_vec (
    int32_t * vec);

/** <No documentation available> */
int32_t *
create_box (void);

/** <No documentation available> */
int32_t *
create_vec (void);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_BDWGC_BOX__ */
