/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_BDWGC_BOX__
#define __RUST_BDWGC_BOX__
#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

/** <No documentation available> */
int32_t
consume_box (
    int32_t * gc);

/** <No documentation available> */
int32_t *
create_box (void);

/** <No documentation available> */
typedef struct GcSlice_int32 {
    /** \brief
     *  TODO
     */
    int32_t * ptr;

    /** \brief
     *  TODO
     */
    size_t len;
} GcSlice_int32_t;

/** <No documentation available> */
GcSlice_int32_t
create_slice (void);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_BDWGC_BOX__ */
